### ISSUE TITLE
Anvil Name Doesn't Reset After Removal of Item

### ISSUE THREAD

**Issue by Thelnfamous1** [Tfarcenim/Anvil-Tweaks#6]
On all versions, when renaming an item and removing it, the anvil doesn't reset the name option to blank and unwriteable and you can still type the name / can't press 'E' to exit the GUI.

**Comment by Tfarcenim** [comment]
try to reproduce on 2.3+ with no other mods

**Comment by Tfarcenim** [comment]
no response = close
