### ISSUE TITLE
Issues loading newest version

### ISSUE THREAD

**Issue by lamoyrl90** [Tfarcenim/Anvil-Tweaks#7]
MC 1.15.2
Anvil Tweaks 2.3
MixinBootstrap 1.0.3

I just updated Anvil Tweaks and I keep getting this critical error

Crash log: https://pastebin.com/0U5J2S8e
Latest.log: https://pastebin.com/iEefGtyu

**Comment by Tfarcenim** [comment]
is this with no other mods?

**Comment by brisingraerowing** [comment]
Testing on my end shows this is a conflict with another mod.

@lamoyrl90 What's your modlist? I can find the intersection of it and my list to narrow down what mod is conflicting.

**Comment by brisingraerowing** [comment]
This is a conflict with Apotheosis.

**Comment by Tfarcenim** [comment]
And it is on apotheosis to fix.

**Comment by Tfarcenim** [comment]
seems like they aren't interested in fixing it.

**Comment by brisingraerowing** [comment]
I saw that. Rather unfortunate.
