### ISSUE TITLE
1.16.3 crash only when Apotheosis and quark is installed with anvil tweaks

### ISSUE THREAD

**Issue by Pet-Slime** [Tfarcenim/Anvil-Tweaks#8]
[crash-2020-10-22_02.56.23-client.txt](https://github.com/Tfarcenim/Anvil-Tweaks/files/5421095/crash-2020-10-22_02.56.23-client.txt)

**Comment by Tfarcenim** [comment]
Apotheosis is incompatible due to it's use of registry replacement and a conflicting coremod.  There are no plans on either side to fix this.
